apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE_NAME}
spec:
  type: ${SERVICE_TYPE}
  ports:
  - port: ${SERVICE_PORT}
    protocol: TCP
    targetPort: ${SERVICE_PORT}
  selector:
    app: ${SERVICE_NAME}
